src/config/config.js
src/config/nunjucks/context/context.test.js
src/server/common/helpers/errors.test.js
src/server/common/templates/layouts/page.njk
src/server/home/index.njk

- **made start page goes no where**
- **start page**

[DSFaap-425] create service start page

---

.github/workflows/check-pull-request.yml
.github/workflows/publish.yml
package-lock.json
package.json
sonar-project.properties
src/server/common/constants/status-codes.js
src/server/common/test-helpers/csrf.js
src/server/common/test-helpers/dom.js
src/server/cph-number/controller.js
src/server/cph-number/controller.test.js
src/server/cph-number/index.njk
src/server/cph-number/validator.js
src/server/exit-page/controller.js
src/server/exit-page/controller.test.js
src/server/exit-page/index.js
src/server/exit-page/index.njk
src/server/on-off-farm/controller.js
src/server/on-off-farm/controller.test.js
src/server/router.js

- **exit page started**
- **trying to get tests working --no-verify**
- **trying to get tests working**
- **updated tests for branch**
- **change title size**

[UNKNOWN] generic exit page

---

src/server/origin-address/controller.test.js
src/server/origin-address/validator.js
src/server/origin-address/validator.test.js

- **added tests and all pass**
- **fixed error message bugs**
- **DSFAAP-453: remove controller comment**
- **DSFAAP-464: lift type definition into param**
- **review comments**
- **sonar cloud fix**
- **DSFAAP-453: joi alternative for validation**
- **fixed tests**
- **run validator and sonarcloud in parralel**
- **updated sonar cloud**
- **updated title**
- **moved back inline to test**
- **nullish coalesce of errors**
- **no magic number**
- **new postcode regex**

[DSFAAP-453] postcode fix

---

src/server/common/controller/question-page-controller.js
src/server/common/controller/question-page-controller.test.js
src/server/common/controller/question-page-controller.test.njk
src/server/common/model/page/question-page-model.js
src/server/common/model/page/question-page-model.test.js
src/server/common/test-helpers/session-helper.js

Yet to implement:
- unsetting state on error

DSFAAP-580: create basic question controller

---

.github/workflows/run-tests-browserstack-desktop.yaml
.github/workflows/run-tests-browserstack-mobile.yaml
src/config/config.js
src/config/nunjucks/context/context.test.js
src/server/common/helpers/errors.test.js
src/server/home/controller.js
src/server/home/controller.test.js
src/server/home/index.njk
src/server/submit/confirmation/index.njk
user-journey-tests/helpers/page.js
user-journey-tests/page-objects/landingPage.js
user-journey-tests/page-objects/page.js
user-journey-tests/page-objects/receiving-the-licence/ownerNamePage.js
user-journey-tests/specs/landing.spec.js
user-journey-tests/specs/taskList.spec.js

- **use service name on start page**
- **add feedback to confirmation page**

[707] feedback link added to confirmation page

---

package-lock.json
src/server/task-list/controller.js
src/server/task-list/controller.test.js

- **redo the work**
- **audit fix**

[743] create log on coming from start page

---

src/server/task-list/controller.js
src/server/task-list/controller.test.js

The best approach now looks to be a search-based one from the existing logs.  See ticket for details.

DSFAAP-743: remove approach failing in test env

---

src/server/common/model/answer/cph-number/cph-number.test.js
src/server/common/model/answer/destination-type/destination-type.test.js
src/server/common/model/answer/email/email-address.test.js
src/server/common/model/answer/kept-separately/kept-separately.test.js
src/server/common/model/answer/on-off-farm/on-off-farm.test.js
src/server/common/model/answer/origin-type/origin-type.test.js
src/server/common/model/answer/receiveMethod/receiveMethod.test.js

The base model classes take responsibility for things like:
- toState / fromState
- html
- stripping characters
The important thing to check is the that these attributes are picked up by the target model (which `isInstanceOf` checks are a proxy for) and that they are configured as expected

DSFAAP-799: simplify tests

---

src/server/biosecurity-map/check-answers/__snapshots__/index.test.js.snap
src/server/biosecurity-map/check-answers/index.js
src/server/biosecurity-map/check-answers/index.test.js
src/server/biosecurity-map/index.js
src/server/biosecurity-map/upload-plan/__snapshots__/index.test.js.snap
src/server/biosecurity-map/upload-plan/index.js
src/server/biosecurity-map/upload-plan/index.njk
src/server/biosecurity-map/upload-plan/index.test.js
src/server/biosecurity-map/upload-progress/index.js
src/server/biosecurity-map/upload-progress/index.test.js
src/server/check-answers/__snapshots__/index.test.js.snap
src/server/check-answers/index.test.js
src/server/common/model/answer/biosecurity-map/biosecurity-map.js
src/server/common/model/answer/biosecurity-map/biosecurity-map.test.js
src/server/common/model/answer/biosecurity-map/validation.js
src/server/common/model/application/application.js
src/server/common/model/page/page-model.js
src/server/common/model/section/biosecurity-plan/biosecurity-plan.js
src/server/common/model/section/biosecurity-plan/biosecurity-plan.test.js
src/server/common/model/state/state-manager.js
src/server/common/templates/macros/create-summary.js
src/server/router.js
src/server/task-list/controller.test.js
user-journey-tests/helpers/testHelpers/biosecurityMap.js
user-journey-tests/helpers/testHelpers/finalAnswers.js
user-journey-tests/page-objects/biosecurity-map/biosecurityMapAnswersPage.js
user-journey-tests/page-objects/taskListPage.js
user-journey-tests/specs/biosecurity-map/biosecurityMapAnswers.spec.js
user-journey-tests/specs/taskList.spec.js

- **added section files**
- **tests fixed**

[782] add bio sec map section

---

src/server/biosecurity-map/upload-plan/index.js

Reverts DEFRA/apha-apps-perms-move-animal-ui#217

Revert "output env vars for uploader to logs"

---

.github/workflows/check-pull-request.yml
compose.yml
package-lock.json
package.json
src/config/config.js
src/server/check-answers/image-compression.js
src/server/check-answers/image-compression.test.js
src/server/check-answers/index.js
src/server/check-answers/index.test.js
src/server/common/helpers/file-size/file-size.js
src/server/common/plugins/s3/index.js
src/server/router.js

- **add file compression**
- **moved image compression to post handler**

[782] image compression logic in place

---

src/server/check-answers/index.test.js

- **dont use File object but use buffers**
- **missed a file**

[DEV] missed a file

---

src/server/origin/index.js
src/server/origin/origin-farm-address/__snapshots__/index.test.js.snap
src/server/origin/origin-farm-address/index.js
src/server/origin/origin-farm-address/index.test.js
user-journey-tests/page-objects/origin/onFarmAddressPage.js
user-journey-tests/specs/origin/dynamicPaths.spec.js
user-journey-tests/specs/origin/onFarmAddress.spec.js

merge & rebase https://github.com/DEFRA/apha-apps-perms-move-animal-ui/pull/232 before starting tests for this

DSFAAP-862: add origin farm address page (for non-import moving on)

---

src/server/origin/import-address/__snapshots__/index.test.js.snap
src/server/origin/import-address/index.js
src/server/origin/import-address/index.test.js
src/server/origin/import-cph/__snapshots__/index.test.js.snap
src/server/origin/import-cph/index.js
src/server/origin/import-cph/index.test.js
src/server/origin/index.js
user-journey-tests/helpers/testHelpers/checkAnswers.js
user-journey-tests/page-objects/origin/checkAnswersPage.js
user-journey-tests/page-objects/origin/importAddressPage.js
user-journey-tests/page-objects/origin/importParishPage.js
user-journey-tests/specs/origin/dynamicPaths.spec.js
user-journey-tests/specs/origin/importAddress.spec.js
user-journey-tests/specs/origin/importParish.spec.js

merge https://github.com/DEFRA/apha-apps-perms-move-animal-ui/pull/241 & rebase before reviewing & merging this

DSFAAP-869: import address

---

.github/workflows/publish.yml
src/server/common/model/answer/validation.js

- **set publish wf to use node 20**
- **set publish wf to use node 20**

[DEV] use node20 for publish

---

src/server/check-answers/__snapshots__/index.test.js.snap
src/server/check-answers/index.js
src/server/check-answers/index.test.js
src/server/common/test-helpers/config.js

- **added in feature flag test**
- **DSFAAP-937: prevent recursion in spyOnConfig**
- **test biosec email variations**

[937] add biosec email variation

---

src/server/biosecurity-map/upload-plan/index.njk

- **add module to script**
- **add module to script**

[1001] attempt at fix

---

src/server/biosecurity-map/upload-plan/index.njk

- **added max file size, and config to tests**
- **update key**

BUG upload env vars

---

user-journey-tests/helpers/testHelpers/movementOrigin.js

Fix race conditions

---

src/index.js
src/server/common/helpers/start-server.js

- **update wreck proxy agent**
- **added missing dep**
- **update wreck proxies with cdp help**

FIXUP wreck uses proxy

---

src/server/common/model/answer/origin-type/origin-type.js
src/server/common/model/answer/origin-type/origin-type.test.js
src/server/origin/origin-type/__snapshots__/index.test.js.snap
user-journey-tests/helpers/testHelpers/destination.js
user-journey-tests/helpers/testHelpers/finalAnswers.js
user-journey-tests/specs/taskList.spec.js

- **add new page and tests**
- **updated lab and other options**

[1123] update origin labels

---

src/server/common/model/answer/destination-type/destination-type.js
src/server/common/model/answer/destination-type/destination-type.test.js
src/server/destination/destination-type/__snapshots__/index.test.js.snap
src/server/destination/destination-type/index.js
src/server/destination/destination-type/index.test.js

- **change destiantion type labels**
- **fixed tests**

[1130] update labels

---

plopfile.js
prompts/question-hint-prompt.js
src/server/exotics/about/animals-id/__snapshots__/index.test.js.snap
src/server/exotics/about/animals-id/index.js
src/server/exotics/about/animals-id/index.test.js
src/server/exotics/about/section.js
templates/question-page/index.js.hbs
templates/question-page/index.test.js.hbs

- **updated tempaltes to support hint text, added id number page**
- **add page to section**

[1328] animals id page

---

src/server/exotics/origin/section.js
src/server/exotics/origin/section.test.js
src/server/exotics/task-list/__snapshots__/index.test.js.snap

- **isVisible and isEnabled implemented and tested**
- **visible and enabled added**

[1333] origin visible/enabled 

---

src/server/exotics/location-of-visit/address/__snapshots__/index.test.js.snap
src/server/exotics/location-of-visit/address/index.js
src/server/exotics/location-of-visit/address/index.test.js
src/server/exotics/location-of-visit/animals-onsite/index.js
src/server/exotics/location-of-visit/section.js

[1364] What is the address of where the visit will take place? 

---

src/config/config.js
src/server/common/connectors/notify/notify.integration.test.js
src/server/common/controller/check-answers-controller/index.js
src/server/common/controller/check-answers-controller/index.test.js
src/server/common/controller/submit-controller/index.js
src/server/common/controller/submit-controller/index.test.js
src/server/exotics/submit/confirmation/index.test.js
src/server/exotics/submit/index.test.js
src/server/tb/submit/confirmation/index.test.js

- **clear application state keeping referencein state**
- **changed stub port**

[1501] clear application state on submission

---

src/server/tb/biosecurity/disinfectant-dilution/__snapshots__/index.test.js.snap
src/server/tb/biosecurity/disinfectant-dilution/index.njk

- **updated copy**
- **updated for undiluted**

[1551] supports undiluted
