user-journey-tests/wdio.browserstack.conf.js
Now that we've merged our UI & UAT repos, it's more natural to call this project UI than UAT in browserstack.
=> BAU: rename browserstack project

compose.yml
Keeping these dependencies around causes our builds to slow down (e.g. fetching & starting images).
I expect we will add some of this back - as necessary - over time.  When we come to that, we can regain this config from history or https://github.com/DEFRA/cdp-node-frontend-template/blob/main/compose.yml.
=> BAU: remove unused docker compose dependencies

src/server/common/model/answer/address.js, src/server/common/model/answer/address.test.js, src/server/common/model/answer/answer-model.js, src/server/common/model/answer/answer-model.test.js, src/server/common/model/answer/confirmation/confirmation.js, src/server/common/model/answer/confirmation/confirmation.test.js, src/server/common/model/answer/cph-number.js, src/server/common/model/answer/cph-number.test.js, src/server/common/model/answer/email-address.js, src/server/common/model/answer/email-address.test.js, src/server/common/model/answer/on-off-farm.js, src/server/common/model/answer/on-off-farm.test.js, src/server/common/model/section/validation.test.js, user-journey-tests/helpers/testHelpers/checkAnswers.js
To ensure only the payload fields we care about are captured in the state, we need to filter them down. 
Otherwise we'll capture things like nextPage & potentially show them to users.
=> DSFAAP-577: filter payload in answer model

src/server/common/model/section/origin.js, src/server/common/model/section/section-model/section-model-updated.js, src/server/common/model/section/section-model/section-model-updated.test.js
[DSFAAP-583: remove unneeded casting](https://github.com/DEFRA/apha-apps-perms-move-animal-ui/commit/31fe47525d1293ff2b1d69b2e47f1ba72892deee)
The page returned by next page could by any instance of Page - e.g. a
summary, exit or question page.
[DSFAAP-583: short-circuit page generation on invalid answer](https://github.com/DEFRA/apha-apps-perms-move-animal-ui/commit/b3519d0377bc943d43a0ae0685fae572098c9baa)
If a user has submitted an invalid answer at any point in the journey,
then there is no well defined output for the nextPage function on a
QuestionPage.
e.g. if you were to not have selected an input to 'Email' or 'Post' for
your licence delivery preference, then that page wouldn't be able to
calculate a next page.
[DSFAAP-583: source Answer class from question …
=> DSFAAP-583: section pages updates

.github/workflows/check-pull-request.yml, .github/workflows/publish.yml
They've issued a deprecation warning for the existing github action, with the text:
>  SonarScanner
> This action is deprecated and will be removed in a future release.
> Please use the sonarqube-scan-action action instead.
> The sonarqube-scan-action is a drop-in replacement for this action.
=> BAU: use recommended sonarcloud action

src/client/stylesheets/core/_all.scss, src/client/stylesheets/core/_main.scss, src/server/common/templates/layouts/page.njk
This additional class causes a difference in the vertical padding between the main content of the prototype & this implementation.
This makes direct comparison between the prototype & implementation more difficult than necessary.
=> BAU: remove app-main wrapper to match prototype

README.md
The default action page shows a list of breakages - but it doesn't make it clear (without some extra eyeball work) which jobs have returned to a good state.
As a result, it's quite easy to miss - in particular - the extended browserstack test failures.
This makes the things that we want to be green all the time obvious - the publish & the extended tests, which both run off the main branch.
=> BAU: add build badges to enhance visibility

.github/workflows/check-pull-request.yml
Github actions have upgraded the test runner for ubuntu-latest from 22.04 to 24.04, which has caused a ChromeDriver not to be able to start chrome & create a session:
> ERROR webdriver: session not created: session not created: Chrome failed to start: exited normally
> [0-2]   (session not created: DevToolsActivePort file doesn't exist)
A longer-term fix involves not depending on the in-built, convenience browser instance from the github runner.  This could be browserstack, or it could be running a selenium docker instance (the approach the CDP template is now taking).
=> BAU: revert ubuntu runner for check prs to 22.04

.github/workflows/run-tests-browserstack-desktop.yaml, .github/workflows/run-tests-browserstack-mobile.yaml, README.md, package.json, user-journey-tests/wdio.browserstack.extended-desktop.conf.js, user-journey-tests/wdio.browserstack.extended-mobile.js
We're seeing multiple intermittent in our browserstack extended tests,
but they only appear to be within iOS.
This creates a 'noisy alert' problem - if we expect our extended tests
to fail frequently, we will start taking test failure less seriously
(since it's likely just the known iOS issue).  Which, in turn, makes it
likely that we'll respond slower to regressions on the stable test run
targets - the desktop browsers.
Separating out the unstable mobile tests from the desktop tests gives us
a functioning test signal again for the desktop arena.
=> BAU: move iOS tests into their own run

.github/workflows/check-pull-request.yml, .github/workflows/publish.yml, Dockerfile, package-lock.json
At present, we have no mechanism for preventing vulnerabilities making it into a production build.
This will cause an error if any vulnerabilities are found in packages we use in production, causing:
- publish job to fail
- check-pullrequest to fail
=> DSFAAP-740: prevent docker image from building with vulns

src/server/common/controller/generic-page-controller/index.js, src/server/common/controller/generic-page-controller/index.test.js
Running unit tests, it was warning of an event emitter leak - and slowing down substantially over time.
Using `node --trace-warnings node_modules/.bin/jest -i`, it identified the createLogger() function call within each of the subclasses.
This is because properties are initialised on class instantiation, so every time we were creating an instance for our classes under test, we were creating a new logger.
I'm removing this for now - to prevent any issues in development - since we're not actively using this logger.
When we need to re-introduce it, we can find a more pino-friendly way to do it.
=> BAU: remove memory-leaking logger we don't yet use

src/server/common/controller/generic-page-controller/index.js, src/server/common/controller/generic-page-controller/index.test.js, src/server/common/model/page/page-model.js
In the CDP platform, we have an nginx cluster in front of the services that gives us logs with messages that look like:
`[response] get /origin/type-of-origin 200 (8ms)`
There are also common fields parsed out - e.g referrer, path, etc
This is already being rendered into a count graph in grafana (based on a lucene query against those logs).  We could make version of the graph that splits that by method and/or url too (with CDP's help), since both are parsed as separate fields from the nginx log.
We don't need to additionally log this manually from the service itself.
=> BAU: remove duplicate metrics

.github/workflows/run-tests-browserstack-desktop.yaml, .github/workflows/run-tests-browserstack-mobile.yaml, user-journey-tests/wdio.browserstack.conf.js
Because of resource limits placed on browserstack, we've experienced a great number of failed test runs that relate to exhausted resources & intermittent browserstack issues.
This also causes failures in our own *publish* job, which is the critical path to production.  The issue is worst when we're at our most productive - merging new code into main.
These tests have rarely uncovered anything that isn't exposed in the user-journey-test run against Chrome, nor against the pair we've introduced for the publish pipeline (so that we're testing on at least a range of desktop browsers before we have a viable build).
As a result, I'm suggesting we push these to late-night cron jobs.  We can see the result in the build radiator style badges on the README in github, and correct if necessary.
=> BAU: run extended browserstack tests at night

src/server/common/controller/question-page-controller/question-page-controller.js, src/server/common/controller/question-page-controller/question-page-controller.test.js, src/server/common/model/answer/answer-model.js, src/server/common/model/answer/answer-model.test.js, src/server/common/model/answer/radio-button/radio-button.js, src/server/common/model/answer/radio-button/radio-button.njk, src/server/common/model/answer/radio-button/radio-button.test.js
Ultimately, I'd like to see us:
- define a view for each Answerodel
- have an answer know how to populate that view (based on its configuration)
As part of the transition, I'm:
- Adding a viewModel to the base AnswerModel class
- passing in the validation options (so the AnswerModel can be responsible for adding the errors itself).
Once we have moved all models over to this way of doing things, we can:
- removing passing the value & errorMessage in via the QuestionPageController
- add the view template to the AnswerModel class itself
- update layouts/questions.njk to look up the view & render it from the AnswerModel class
Note that the viewModel for a class can return anything that satisfies its own template.  There's no one-size-fits-all expectation for viewModels across types such as …
=> BAU: lift viewModel into a generic AnswerModel fn

src/server/check-answers/__snapshots__/index.test.js.snap, src/server/check-answers/index.njk
This text seems (to me) to be the closest to an appropriate label we have for the checkboxes.  I think it fits with what a user would want to hear (and would hear)  the guidance given here: https://accessibility.blog.gov.uk/2016/07/22/using-the-fieldset-and-legend-elements/
It does change the whitespace subtly.  Our version looks like:
Where's the [prototype (v2_0_0)](https://applicationsandpermissions-dev-ffeda85e15b1.herokuapp.com/v2_0_0/create-application/submit/check-answers) looks like:
Looking at the prototype HTML, I think the accessibility audit would pick up an issue with the prototype too.
=> DSFAAP-765: add a label to final answers checkbox

.github/workflows/publish.yml
Similar to the current check-pull-request.yml job, when we're running directly against chromium, we need to pin it to an older github action runner
Addressing this piece of tech debt is covered in DSFAAP-644 (whose ACs I've changed to cover the publish.yml job too)
=> DSFAAP-808: pin to ubuntu 22.04

src/server/common/controller/question-page-controller/question-page-controller.js, src/server/common/controller/question-page-controller/question-page-controller.test.js, src/server/common/model/page/question-page-model.js
In Release 2, we have some pages that show up depending on *both* the answer to the current question and prior application state.
To facilitate this, routing decisions need to know about both:
- the immediate answer given
- the historical answers given
For instance, after the origin type question, the user is routed to a different CPH number & Address page depending on whether you're going on the premises or off the premises.
=> BAU: allow routing to depend on whole app state

src/server/common/model/answer/origin-type/origin-type.js, src/server/common/model/answer/origin-type/origin-type.test.js, src/server/common/model/answer/radio-button/radio-button.js, src/server/common/model/answer/radio-button/radio-button.test.js, src/server/common/model/page/question-page-model.js, src/server/common/model/section/section-model/section-model.js, src/server/origin/country/index.js, src/server/origin/fifty-percent-warning/index.js, src/server/origin/origin-farm-cph/index.js, src/server/origin/origin-type/index.js, src/server/origin/origin-type/index.test.js, user-journey-tests/helpers/testHelpers/checkAnswers.js, user-journey-tests/page-objects/origin/fiftyPercentPage.js, user-journey-tests/page-objects/origin/onFarmCPHPage.js, user-journey-tests/page-objects/origin/originCountryPage.js, user-journey-tests/page-objects/origin/originTypePage.js, user-journey-tests/specs/origin/toFromFarm.spec.js
I've added the option to pass a config factory.  This allows us to:
1. change the *option* text, without changing the value
2. change the *order* of options, even when options are the same
The first one is necessary for this ticket - where the concept of
'other' premise has an updated label (and yet we're implementing this in
a way that preserves the current implementation that's accessible in
live).
The second one will be necessary for future tickets (specifically
destination premises type), where the order for each option has been
user test specifically & helps users answer the question.
=> DSFAAP-853: Allow dynamic radio button configuration & implement routing for origin type

user-journey-tests/specs/landing.spec.js
Previously, the test would exit without waiting on the result of forEach.
In this iteration, each link's test result is awaited (and it fails if the list of expected links does not contain the links that are actually on the page).
=> DSFAAP-921: fix race condition in link tests

src/server/biosecurity-map/upload-plan/index.js, src/server/biosecurity-map/upload-progress/index.js, src/server/common/controller/question-page-controller/question-page-controller.js, src/server/common/model/state/state-manager.js, src/server/common/model/state/state-manager.test.js, src/server/licence/postExitPage/post-exit-page-controller.js
The state update operation is dangerous (because you could wipe out the other state in your relevant section), so I'm not keen to repeat it across our codebase.
In upcoming change (to handle pdfs that cannot compress) will introduce another place where we use this pattern, so I wanted to extract it ahead of that.
=> BAU: Do state updates in the StateManager

user-journey-tests/helpers/authSessionManager.js, user-journey-tests/specs/destination/destinationAnswers.spec.js, user-journey-tests/specs/destination/destinationSelectionOptions.spec.js
In the application, there are 4 cookies:
- defra-id-bell
- userSession
- session
- crumb
The login-specific cookies are defra-id-bell and userSession - with userSession being the one that tells the application that the user is successfully signed in.
Session and (to a lesser extent) crumb are the cookies that manage application state and user journey aside from authorisation.
e.g. where are you in the journey, and whether your page submission is believed to be legitimate.
This PR deletes only the application state cookies, keeping the auth ones in place.
Also, by doing this we avoid global state, which opens up to (e.g.) having multiple test accounts with different roles in future, without tests conflicting with each other.
=> BAU: simplify test login management

src/server/common/model/answer/date/date-utils.js, src/server/common/model/answer/date/date-utils.test.js
We want our date comparisons to:
- always represent the date submitted by the user as though it's a Europe/London date (e.g. accounting for BST in the summer months)
- no matter what timezone the system time is set to, use the date it would be in `Europe/London` at that point in time as our point of comparison
I think these tests help to capture that coverage more accurately - and they've shown that a simpler implementation can have the desired effect.
=> DSFAAP-1056: suggested test improvements & refactor

src/server/common/helpers/auth/defra-id.js
The pino library expects either:
- a string *or*
- a context object followed by a string
The logging statement - as was - caused the first part to be output, but never output the OIDC url that was being used.
=> BAU: fix DEFRA OIDC logging
